// Workout action types
export const FETCH_WORKOUTS_REQUEST = 'FETCH_WORKOUTS_REQUEST';
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS';
export const FETCH_WORKOUTS_FAILURE = 'FETCH_WORKOUTS_FAILURE';

export const FETCH_WORKOUT_REQUEST = 'FETCH_WORKOUT_REQUEST';
export const FETCH_WORKOUT_SUCCESS = 'FETCH_WORKOUT_SUCCESS';
export const FETCH_WORKOUT_FAILURE = 'FETCH_WORKOUT_FAILURE';
export const ADD_WORKOUT_REQUEST = 'ADD_WORKOUT_REQUEST';
export const ADD_WORKOUT_SUCCESS = 'ADD_WORKOUT_SUCCESS';
export const ADD_WORKOUT_FAILURE = 'ADD_WORKOUT_FAILURE';

// Peak Force action types
export const FETCH_PEAK_FORCES_REQUEST = 'FETCH_PEAK_FORCES_REQUEST';
export const FETCH_PEAK_FORCES_SUCCESS = 'FETCH_PEAK_FORCES_SUCCESS';
export const FETCH_PEAK_FORCES_FAILURE = 'FETCH_PEAK_FORCES_FAILURE';

export const FETCH_PEAK_FORCE_REQUEST = 'FETCH_PEAK_FORCE_REQUEST';
export const FETCH_PEAK_FORCE_SUCCESS = 'FETCH_PEAK_FORCE_SUCCESS';
export const FETCH_PEAK_FORCE_FAILURE = 'FETCH_PEAK_FORCE_FAILURE';

// User action types
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

